package com.app.ecarepro.ui.edit_profile.model.update_profile

data class StudentProfile(
    var aadhaarNumber: String,
    var address: String,
    var birthPlace: String,
    var city: String,
    var contactEmailID: String,
    var contactMobile: String,
    var fatherAadhaarNumber: String,
    var fatherAnnualIncome: String,
    var fatherDOB: String?,
    var fatherEmail_1: String,
    var fatherEmail_2: String,
    var fatherMob_1: String,
    var fatherMob_2: String,
    var fatherOfficeAddress: String,
    var fatherResidentialAddress: String,
    var motherAadhaarNumber: String,
    var motherAnnualIncome: String,
    var motherDOB: String?,
    var motherEmail_1: String,
    var motherEmail_2: String,
    var motherMob_1: String,
    var motherMob_2: String,
    var motherOfficeAddress: String,
    var motherResidentialAddress: String,
    var parentAnniversaryDate: String?,
    var permanentAddress: String,
    var permanentCity: String,
    var permanentState: String,

    var state: String,
    var previousSchoolDTL: PreviousSchoolDTL,
)