package com.app.ecarepro.ui.fom_guard.model.verify_code

data class Appdetails(
    val address: String,
    val appointmentDuration: String,
    val appointmentStatus: String,
    val appointmentid: Int,
    val appointmentno: String,
    val autoOutTime: Boolean,
    val checkInTime: String,
    val checkOutTime: String,
    val coVisitorone: String,
    val coVisitorthree: String,
    val coVisitortwo: String,
    val company: String,
    val department: String,
    val designation: String,
    val email: String,
    val employeeName: String,
    val formtype: String,
    val idNo: String,
    val idType: String,
    val mobile: String,
    val name: String,
    val noOfCovisitors: String,
    val otherPurposeText: String,
    val purpose: String,
    val visitingDate: String,
    val visitingTime: String,
    val visitorPhoto: String,
    val visitorType: String
)