package com.app.ecarepro.model

data class LessonPlan(
    val actionTakenBy: Any,
    val attachment: AttachmentView?,
    val auditoryIds: String,
    val auditoryTxt: String,
    val classIds: String,
    val classesName: String,
    val closure: String,
    val createdOn: Any,
    val extensionTopic: String,
    val fileName: String,
    val fromDate: String,
    val id: String,
    val introduction: String,
    val kinestheticActivity: String,
    val lPlnID: Int,
    val learningOutcomes: String,
    val objective: String,
    val otherResources: String,
    val rejectionComments: String,
    val resources: String,
    val showToStudent: Boolean,
    val status: Int,
    val subID: Int,
    val subject: String,
    val teacherID: Int,
    val teacherName: Any,
    val tillDate: String,
    val topic: String,
    val youtubeLinks: String
)