package com.app.ecarepro.ui.edit_profile.staff.model.payload

data class StaffUpdateModel(
    val address: String?,
    val alternateEmailID: String?,
    val alternateMobile: String?,
    val bloodGroupID: Int?,
    val cbseid: String?,
    val doAnniversary: String?,
    val dob: String?,
    val doj: String?,
    val emailID: String?,
    val emergencyContactNo: String?,
    val fName: String?,
    val fatherHusbandMob: String?,
    val fatherHusbandName: String?,
    val isMaritialStatusID: Boolean?,
    val isNationalityID: Boolean?,
    val isRelationshipWithMemberId: Boolean?,
    val isRelegionID: Boolean?,
    val isTitleID: Boolean?,
    val lName: String?,
    val mName: String?,
    val maritialStatusID: Int?,
    val nationalCode: String?,
    val nationalityID: Int?,
    val p_Address: String?,
    val paN_Number: String?,
    val qualification: String?,
    val relationshipWithMemberId: Int?,
    val relegionID: Int?,
    val stateCode: String?,
    val titleID: Int?,
    val uaN_Number: String?
)